2022-06-20 08:38:00,649 - [WARNING] - distributor - (distributor.py).create_connection(37) - The error connection to server at "10.93.63.13", port 5432 failed: Connection timed out (0x0000274C/10060)
	Is the server running on that host and accepting TCP/IP connections?
 occurred
2022-06-20 10:03:14,662 - [WARNING] - client - (client.py).create_client_post_alpha(35) - Connection to slave server: opc.tcp://10.93.63.10:62544
2022-06-20 13:10:34,389 - [WARNING] - client - (client.py).create_client_post_alpha(36) - Connection to slave server: opc.tcp://10.93.63.10:62544
2022-06-20 13:19:20,881 - [WARNING] - client - (client.py).create_client_post_alpha(36) - Connection to slave server: opc.tcp://127.0.0.1:4050
2022-06-20 13:19:47,872 - [WARNING] - client - (client.py).create_client_post_alpha(36) - Connection to slave server: opc.tcp://127.0.0.1:4050
2022-06-20 13:21:40,228 - [WARNING] - client - (client.py).create_client_post_alpha(36) - Connection to slave server: opc.tcp://127.0.0.1:4050
